#! /usr/bin/env  bash
# Copyright 2024 Raphael Thomazella. All rights reserved.
# Use of this source code is governed by the BSD-3-Clause
# license that can be found in the LICENSE file and online
# at https://opensource.org/license/BSD-3-clause.

set -euo pipefail
shopt -s globstar
trap 'echo fatal: $0:$LINENO >&2' ERR

cmd="${1:-help}"

case "$cmd" in
bench:*)
  exec bench/run "${cmd#bench:}"
  ;;
keys:*)
  exec keys/run "${cmd#keys:}"
  ;;
help | *)
  echo "Usage: ./run <prefix>:<command>"
  echo "Prefixes:"
  echo "  bench:  bench mcp commands"
  echo "  keys:   keys mcp commands"
  echo ""
  echo "bench:"
  bench/run help | tail -n +4
  echo ""
  echo "keys:"
  keys/run help | tail -n +4
  ;;
esac
