# this file has example values in the volumes section
volumes:
  bench-mcp-mise:
  bench-mcp-root:

services:
  bench-mcp:
    container_name: bench-mcp-stdio
    image: ghcr.io/rthomazel/mcp/bench:latest
    stdin_open: true
    tty: false
    environment:
      # timeout for shell commands
      BENCH_MCP_TIMEOUT: 15s
      # timeout for shell background
      BENCH_MCP_BACKGROUND_TIMEOUT: 5m
    volumes:
      # persistent state: mise installs and shims, Go cache, path snapshot
      - bench-mcp-mise:/mise
      - bench-mcp-root:/root
      # >>> add projects below here <<<
      # host machine path : container path
      - /Users/you/helloworld:/projects/helloworld
