name: bench pr
run-name: ${{ github.head_ref }}@${{ github.sha }}

on:
  pull_request:
    branches: [main]
    paths:
      - 'bench/**'
      - '.github/workflows/bench-pr.yml'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7

      - uses: actions/setup-go@v5.0.2
        with:
          go-version: "1.26"

      - run: ./run bench:build:go

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7

      - uses: actions/setup-go@v5.0.2
        with:
          go-version: "1.26"

      - run: go install github.com/joho/godotenv/cmd/godotenv@v1.5.1
      - run: cp bench/.env-default bench/.env && ./run bench:test

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7

      - uses: actions/setup-go@v5.0.2
        with:
          go-version: "1.26"

      - uses: golangci/golangci-lint-action@v9
        with:
          version: v2.10
          working-directory: bench

  go-mod:
    name: go_mod_tidy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7

      - uses: actions/setup-go@v5.0.2
        with:
          go-version: "1.26"

      - uses: j0hnsmith/go-mod-check@v1.0.0
        with:
          working-directory: bench

  changelog:
    name: changelog
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - name: check CHANGELOG.md is updated
        run: |
          if git diff --name-only origin/main...HEAD | grep -q '^bench/CHANGELOG.md$'; then
            echo "CHANGELOG.md is updated."
          else
            echo "::warning::CHANGELOG.md was not updated in this PR."
            exit 1
          fi
